# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

# common: &common
#   adapter: postgresql
#   username: fredbook
#   password: ppassword # from psql setup, see Postgresql

development:
  adapter: postgresql
  username: fredbook
  database: wedding_dev

test:
  adapter: postgresql
  username: fredbook
  database: wedding_test

production:
  adapter: postgresql
  username: fredbook
  database: wedding_production

